### ISSUE TITLE
Passing Command Line Arguments to games

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/web#7]
Is there currently a way to pass arguments to games after they are loaded in the web program?  After skimming the code, I don't believe there is. Command line args are pretty important, especially to patched/localized versions of System 1-3 games, which basically need the -game argument. I wanted to make sure I hadn't overlooked anything.  Sorry if I did!

It would be nice to, say, include an args.txt file in the GAMEDATA folder to specify your desired command line arguments.

**Comment by kichikuou** [comment]
Currently there's no way to set command line arguments from user-provided files.

For testing purposes, URL parameters starting with `-` are passed to system3/xsystem35 as arguments. For example, this launches the emscripten binary with `-game little_vampire` option:
https://kichikuou.github.io/web/?-game=little_vampire

Rather than relying on the `-game` flag, I think it would be better if system3 could recognize the game by CRC32 like this:
https://github.com/kichikuou/system3-sdl2/compare/crc32

Would this approach work for you?

**Comment by RottenBlock** [comment]
Is the CRC32 identical across patches? I'd swear I've had problems with it in the past, though I admit I can't seem to duplicate them. My mistake then, which is fine as far as the -game flag is concerned.  Unfortunately, I do still want to use other flags. For the time being, I'll use the URL parameters you mentioned, thanks!

**Comment by kichikuou** [comment]
After kichikuou/system3-sdl2@14f4c38, `system3` loads [`system3.ini` file](https://github.com/kichikuou/system3-sdl2#configuration-file-system3ini) at startup.

Now you can create a zip for the web app that includes `system3.ini` file with the following contents for example:

```
[config]
game = little_vampire
fontfile = customfont.ttf
```

This will have the same effect as specifying `-game little_vampire -fontfile customfont.ttf` on the command line.

**Comment by RottenBlock** [comment]
Thank you! This is just what it needed.
